import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Deepak',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 10),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 10),
      isAdmin: false,
    },    
  ],

  products: [
    {
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 77.80,
      countInStock: 10,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 66451,
      description: 'high quality product',
    },
    {
      name: 'Nike Kids Shoes',
      category: 'Shoes',
      image: '/images/p2.jpg',
      price: 76.80,
      countInStock: 20,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 56321,
      description: 'high quality product',
    },
    {
      name: 'UnderArmour Tshirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 120.80,
      countInStock: 0,
      brand: 'UnderArmour',
      rating: 4.0,
      numReviews: 4564510,
      description: 'Skin fit Tshirt',
    },
    {
      name: 'Polo Ellite TShirt',
      category: 'Shirts',
      image: '/images/p4.jpg',
      price: 54.34,
      countInStock: 10,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 6456310,
      description: 'Soft Texture Polo Shirt',
    },
    {
      name: 'EddieBauer Shirt',
      category: 'Shirts',
      image: '/images/p5.jpg',
      price: 120.80,
      countInStock: 40,
      brand: 'EddieBauer',
      rating: 3.5,
      numReviews: 86765710,
      description: 'Comfy fit Ellegant white Women\'s Shirt',
    },
    {
      name: 'Levis Women\'s Shorts',
      category: 'Shorts',
      image: '/images/p6.jpg',
      price: 54.80,
      countInStock: 100,
      brand: 'Levis',
      rating: 4.7,
      numReviews: 54644610,
      description: 'Short Denim Trendy women blue',
    },
    {
      name: 'Wrangler Women\'s Shorts',
      category: 'Shorts',
      image: '/images/p7.jpg',
      price: 86.80,
      countInStock: 90,
      brand: 'Wrangler',
      rating: 4.5,
      numReviews: 7456710,
      description: 'Short Denim Trendy women gray',
    },
    {
      name: 'Nike Kid\'s Jacket',
      category: 'Jackets',
      image: '/images/p8.jpg',
      price: 32.80,
      countInStock: 11,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 104564,
      description: 'high quality product',
    },
    {
      name: 'Zing Women\'s Skirts',
      category: 'Skirts',
      image: '/images/p9.jpg',
      price: 76.80,
      countInStock: 1,
      brand: 'Zing',
      rating: 4.5,
      numReviews: 5234510,
      description: 'high quality product',
    },
    {
      name: 'Calvin Klein Slim Shirt',
      category: 'Shirts',
      image: '/images/p10.jpg',
      price: 34.80,
      countInStock: 1,
      brand: 'Calvin Klein',
      rating: 3.5,
      numReviews: 1452340,
      description: 'high quality product',
    },
    {
      name: 'Diesel Men\'s Formal Pants',
      category: 'Pants',
      image: '/images/p11.jpg',
      price: 57.80,
      countInStock: 44,
      brand: 'Diesel',
      rating: 3.5,
      numReviews: 15253450,
      description: 'high quality product',
    },
    {
      name: 'Zing Women\'s Shirts',
      category: 'Shirts',
      image: '/images/p12.jpg',
      price: 90.80,
      countInStock: 65,
      brand: 'Zing',
      rating: 4.3,
      numReviews: 10545454,
      description: 'high quality product',
    },
    {
      name: 'Polo Ralph Lauren Jeans Pants',
      category: 'Pants',
      image: '/images/p13.jpg',
      price: 67.80,
      countInStock: 55,
      brand: 'Polo Ralph Lauren',
      rating: 4.1,
      numReviews: 4524510,
      description: 'high quality product',
    },
    {
      name: 'Dawson Denim Women\'s Pants',
      category: 'Pants',
      image: '/images/p14.jpg',
      price: 80.80,
      countInStock: 34,
      brand: 'Dawson Denim',
      rating: 4.2,
      numReviews: 656410,
      description: 'high quality product',
    },
    {
      name: 'Ultranice Women\'s Summer Short Sleeve Casual Dress',
      category: 'Dresses',
      image: '/images/p15.jpg',
      price: 65.80,
      countInStock: 67,
      brand: 'Ultranice',
      rating: 4.4,
      numReviews: 342510,
      description: 'high quality product',
    },
  ],
}

export default data
