const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 77.34,
      countInStock: 10,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 66451,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 76.85,
      countInStock: 20,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 56321,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 120.1,
      countInStock: 0,
      brand: 'Nike',
      rating: 4.0,
      numReviews: 4564510,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p4.jpg',
      price: 54.5,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 6456310,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p5.jpg',
      price: 120.0,
      countInStock: 40,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 86765710,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p6.jpg',
      price: 86.0,
      countInStock: 90,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 7456710,
      description: 'high quality product',
    },
    {
      _id: '7',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p7.jpg',
      price: 54.556,
      countInStock: 100,
      brand: 'Nike',
      rating: 4.7,
      numReviews: 54644610,
      description: 'high quality product',
    },
    {
      _id: '8',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p8.jpg',
      price: 32.77,
      countInStock: 11,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 104564,
      description: 'high quality product',
    },
    {
      _id: '9',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p9.jpg',
      price: 76.1,
      countInStock: 1,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 5234510,
      description: 'high quality product',
    },
    {
      _id: '10',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p10.jpg',
      price: 34.55,
      countInStock: 1,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 1452340,
      description: 'high quality product',
    },
    {
      _id: '11',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p11.jpg',
      price: 57.0,
      countInStock: 44,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 15253450,
      description: 'high quality product',
    },
    {
      _id: '12',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p12.jpg',
      price: 90.75,
      countInStock: 65,
      brand: 'Nike',
      rating: 4.3,
      numReviews: 10545454,
      description: 'high quality product',
    },
    {
      _id: '13',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p13.jpg',
      price: 67.35,
      countInStock: 55,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 4524510,
      description: 'high quality product',
    },
    {
      _id: '14',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p14.jpg',
      price: 80.0,
      countInStock: 34,
      brand: 'Nike',
      rating: 4.2,
      numReviews: 656410,
      description: 'high quality product',
    },
    {
      _id: '15',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p15.jpg',
      price: 65.0,
      countInStock: 67,
      brand: 'Nike',
      rating: 4.4,
      numReviews: 342510,
      description: 'high quality product',
    },
  ],
}

export default data
